BuyIt/urls.py
from django.urls import path
from . import views

app_name="BuyIt"


urlpatterns = [
    path("", views.index, name="index"),
    path("item/<int:it>", views.item,name="item"),
    path("about/", views.about, name="about"),
    path("profile/",views.profile, name= "profile")
]

KnowIt/urls.py
from django.urls import path
from . import views

app_name="KnowIt"

urlpatterns = [
    path("index", views.index, name="index"),
    path("physicists/", views.physicists, name="physicists"),
    path("form/",views.form,name="form"),
    path("form/display",views.display,name="display")
]

cart/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path("",views.cart_summary,name="cart_summary"),
    path("delete/",views.cart_delete,name="cart_delete"),
    path("add/", views.cart_add, name="cart_add"),
    path("update/", views.cart_update, name="cart_update")
]

django_prac/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),
    path('',include("members.urls")),
    path('KnowIt/',include("KnowIt.urls")),
    path('BuyIt/',include("BuyIt.urls")),
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include("members.urls")),
    path('cart/',include("cart.urls")),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

members/urls.py
from django.contrib import admin
from django.urls import include,path
from . import views

app_name="members"

urlpatterns = [
    path("", views.login_user, name="login_user"),
    path("logout_user",views.logout_user,name="logout_user"),
    path("register_user",views.register_user,name="register_user"),
    path("mugen",views.mugen,name="mugen"),
    path("update_user", views.update_user, name="update_user")
]

BuyIt/models.py
from django.db import models

# Create your models here.


class Product(models.Model):
    name = models.CharField(max_length=100)
    img = models.ImageField(upload_to='pics')
    tag = models.TextField(max_length=100,default='000000')
    desc = models.TextField(max_length=100000)
    price = models.IntegerField()
    offer = models.BooleanField(default=False)

KnowIt/models.py
from django.db import models

# Create your models here.


class Destination(models.Model):
    name = models.CharField(max_length=100)
    img = models.ImageField(upload_to='pics')
    desc = models.TextField(max_length=100)
    price = models.IntegerField()
    offer = models.BooleanField(default=False)

cart/models.py
from django.db import models

# Create your models here.

BuyIt/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Product
from django.contrib.auth.models import User
 

# Create your views here.
app_name='BuyIt'

def index(request):
    Product1= Product.objects.all()
    return render(request, "BuyIt/index.html",{'Products' : Product1})

def item(request,it):
    items= Product.objects.get(id=it)
    return render(request, "BuyIt/item.html",{'items' : items})

def about(request):
    return render(request,"BuyIt/about.html")
    
def profile(request):
    user = request.user
    user = {
            'username': user.username,
            'email': user.email,
            'first_name': user.first_name,
            'last_name': user.last_name,
            'date_joined': user.date_joined,
            'last_login' : user.last_login
        }
    return render(request, "BuyIt/profile.html", user)

KnowIt/views.py
from django.shortcuts import render
from django.http import HttpResponse


form1 = []
def index(request):
    return render(request,"KnowIt/index.html")
def physicists(request):
    return render(request,"KnowIt/physicists.html")
def form(request):
    return render(request,"KnowIt/form.html")

def display(request):
    email = request.POST['inlineFormInputGroupUsername']
    #value = request.GET['inlineFormCheck']
    form = [email]
    return render(request,"KnowIt/display.html",{"form": form})

cart/views.py
from django.shortcuts import render,get_object_or_404, render
from .cart import Cart
from BuyIt.models import Product
from django.http import JsonResponse
from django.contrib import messages


# Create your views here.
app_name='cart'


def cart_summary(request):
    cart = Cart(request)
    products= cart.get_prod
    cart_total = cart.cart_total()
    return render(request,"cart/cart_summary.html",{"products": products, 'cart_total':cart_total})

def cart_update(request):
    return render(request,"cart/cart_summary.html",{})

def cart_add(request):
    cart=Cart(request)
    if request.POST.get('action')== 'post':
        product_id = int(request.POST.get('product_id'))
        product = get_object_or_404(Product, id= product_id)
        print(product)
        cart.add(product=product)
        cart_quantity = cart.__len__()
        cart_total = cart.cart_total()
        response = JsonResponse({ 'Qty':cart_quantity , 'cart_total':cart_total})
        messages.success(request,("Yay!! Item added to cart Succesfully..!"))
        return response

def cart_delete(request):
    cart=Cart(request)
    if request.POST.get('action')== 'post':
        product_id = int(request.POST.get('product_id'))
        cart.delete(product = product_id)
        response = JsonResponse({'deleted':product_id})
        messages.success(request,("Item deleted from cart succesfully"))
        return response

members/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from django.contrib.auth.models import User, auth
import copy
from cart.cart import Cart
from django_prac import settings

# Create your views here.

def login_user(request):
    if request.method=="POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("members:mugen")
        else:
           messages.success(request,("Please enter right username/password and try again!!"))
           return redirect("members:login_user")
    else:
     return render(request, "members/login_user.html", {})


def register_user(request):
    if request.method=="POST":
        username = request.POST["username"]
        first_name = request.POST["first_name"]
        last_name = request.POST["last_name"]
        email = request.POST["email"]
        password =request.POST["password"]
        password1 = request.POST["re-password"]
        if User.objects.filter(username=username).exists():
           messages.info(request,"Username is already taken, please try with other username")
           return redirect("members:register_user")
        elif User.objects.filter(email=email).exists():
           messages.info(request,"Sorry! Email already exists, try giving another one")
           return redirect("members:register_user")
        elif password==password1:
            user = User.objects.create_user(username=username,password=password1,email=email,first_name=first_name,last_name=last_name)
            user.save()
            messages.info(request,"Congrats!! User created successfully")
            return redirect("members:register_user")
        else:
           messages.info(request,"Passwords dosent match, please re-enter")
           return redirect("members:register_user")
    else:
       return render(request, "members/register_user.html",{})

def logout_user(request):
   cart = copy.deepcopy(Cart(request).cart)
   session = request.session
   print(session.get('session_key'))
   session.modified = True
   messages.success(request,("Successfully logged out!!"))
   logout(request)
   return redirect("members:login_user")

def mugen(request):
   messages.success(request,("You are successfully logged in!!"))
   return render(request, "members/mugen.html",{})

def update_user(request):
   
   return(request, "members/update_user.html",{})

BuyIt/templates/BuyIt/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>BuyIT</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    </head>
    <body>
      <div style="margin-bottom:8%;">
        <nav class="navbar navbar-expand-lg bg-body-tertiary fixed-top">
            <div class="container-fluid">
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
                <a class="navbar-brand" href="{% url 'BuyIt:index' %}">Buy <span style="color:aqua;">IT</span></a>
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'BuyIt:index' %}">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'BuyIt:about' %}">About Us</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Write to Us</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'members:logout_user' %}">Logout</a>
                  </li>
                </ul>
                <!-- <a href="{% url 'cart_summary' %}" class="btn btn-outline-success" style="color: black;" tabindex="-1" role="button"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bag inline-block align-middle" viewBox="0 0 16 16">
                  <path d="M8 1a2.5 2.5 0 0 1 2.5 2.5V4h-5v-.5A2.5 2.5 0 0 1 8 1m3.5 3v-.5a3.5 3.5 0 1 0-7 0V4H1v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V4zM2 5h12v9a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1z"/>
                </svg> <span style="font-weight: lighter;" class="inline-block align-bottom">   My Cart</span><span class="badge bg-dark text-white ms-1 rounded-pill" id="cart_quantity"> {{ cart|length }}</span></a>
              -->
                  <a href="{% url 'BuyIt:profile'%}" style="color: black; text-decoration: none; margin-right: 10px; border-style:solid; border-radius: 35px; padding: 5px; border-color: aqua;"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" style="width: 20px;"><!--!Font Awesome Free 6.7.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2025 Fonticons, Inc.--><path d="M304 128a80 80 0 1 0 -160 0 80 80 0 1 0 160 0zM96 128a128 128 0 1 1 256 0A128 128 0 1 1 96 128zM49.3 464l349.5 0c-8.9-63.3-63.3-112-129-112l-91.4 0c-65.7 0-120.1 48.7-129 112zM0 482.3C0 383.8 79.8 304 178.3 304l91.4 0C368.2 304 448 383.8 448 482.3c0 16.4-13.3 29.7-29.7 29.7L29.7 512C13.3 512 0 498.7 0 482.3z"/></svg>Profile</a>
                  <a href="{% url 'cart_summary' %}" type="button" class="btn btn-outline-success position-relative" style="width: 130px;">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bag inline-block align-middle" viewBox="0 0 16 16">
                  <path d="M8 1a2.5 2.5 0 0 1 2.5 2.5V4h-5v-.5A2.5 2.5 0 0 1 8 1m3.5 3v-.5a3.5 3.5 0 1 0-7 0V4H1v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V4zM2 5h12v9a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1z"/>
                  </svg><span style="margin-left:5px">My cart</span>
                  <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                     {{ cart|length }}
                    <span class="visually-hidden">my cart</span>
                  </span>
                </a>
              </div>
            </div>
          </nav>
        </div>
        {% if messages %}
          {%for message in messages%}
            <div class="alert alert-success" role="alert">
              {{message}}
            </div>
          {%endfor%}
        {%endif%}
        {% block body %}
        {%endblock%}
        <div id="footer" style="color: black; width: 100%; background-color: rgb(182, 174, 174); height: 100px; text-align: center; bottom: 0;">
          <div id="footer-links" style="word-spacing: 20px;">
              <a href="https://www.instagram.com/anjaneesh_v?igsh=MWg0bW02aThuanJ1Yg%3D%3D&utm_source=qr" style="color: white; text-decoration: none;"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
                  <path  d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.9 3.9 0 0 0-1.417.923A3.9 3.9 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.9 3.9 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.9 3.9 0 0 0-.923-1.417A3.9 3.9 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599s.453.546.598.92c.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.5 2.5 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.5 2.5 0 0 1-.92-.598 2.5 2.5 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233s.008-2.388.046-3.231c.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92s.546-.453.92-.598c.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92m-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217m0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334"/>
              </svg></a>
              <a href="https://github.com/Anjaneesh-valluri" style="color: white; "><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
                  <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27s1.36.09 2 .27c1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0 0 16 8c0-4.42-3.58-8-8-8"/>
              </svg></a>
          </div>
          <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.05); width: 100%;">
              © 2020 Copyright:
              <a class="text-body" href="{% url 'BuyIt:index' %}">BuyIt.com</a>
          </div>
        </div>
    </body>
</html>

KnowIt/templates/KnowIt/display.html
{% extends "KnowIt/layout.html" %}
{% block body %}

<p style="margin-top: 60px;"> Here is the response</p>
<p>{{form}}</p>


{% endblock %}

KnowIt/templates/KnowIt/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>KnowIt</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    </head>
    <body style="background-color: gray;">
        <nav class="navbar navbar-dark bg-dark fixed-top">
            <div class="container-fluid">
              <a class="navbar-brand" href="{% url 'KnowIt:index' %}">Know <span style="color: chartreuse;">It</span></a>
              <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
                <div class="offcanvas-header">
                  <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">Menu</h5>
                  <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                </div>
                <div class="offcanvas-body">
                  <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                    <li class="nav-item">
                      <a class="nav-link active" aria-current="page" href="{% url 'KnowIt:index' %}">Home</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'KnowIt:form' %}">Write to us</a> 
                    </li>
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Go to
                      </a>
                      <ul class="dropdown-menu dropdown-menu-dark">
                        <li><a class="dropdown-item" href="{% url 'KnowIt:physicists' %}">Physicists</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li>
                          <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="{% url 'BuyIt:index' %}">Got to Buy <span style="color: darkcyan;">It</span></a></li>
                      </ul>
                    </li>
                  </ul>
                  <form class="d-flex mt-3" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-success" type="submit">Search</button>
                  </form>
                </div>
                <div style="text-align: center; margin-bottom: 6%;">
                    <a  href="{% url 'members:logout_user' %}" style="text-decoration: none;"><span style="color: rgb(227, 64, 64);">Logout</span></a>             
                </div>
              </div>
            </div>
          </nav>
        {% block body %}
        {% endblock %}
        <div id="footer" style="color: white; width: 100%; background-color: black; height: 100px; text-align: center; bottom: 0;">
            <div id="footer-links" style="word-spacing: 20px;">
                <a href="https://www.instagram.com/anjaneesh_v?igsh=MWg0bW02aThuanJ1Yg%3D%3D&utm_source=qr" style="color: white; text-decoration: none;"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
                    <path  d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.9 3.9 0 0 0-1.417.923A3.9 3.9 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.9 3.9 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.9 3.9 0 0 0-.923-1.417A3.9 3.9 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599s.453.546.598.92c.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.5 2.5 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.5 2.5 0 0 1-.92-.598 2.5 2.5 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233s.008-2.388.046-3.231c.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92s.546-.453.92-.598c.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92m-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217m0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334"/>
                </svg></a>
                <a href="https://github.com/Anjaneesh-valluri" style="color: white;"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
                    <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27s1.36.09 2 .27c1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0 0 16 8c0-4.42-3.58-8-8-8"/>
                </svg></a>
            </div>
            <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.05); width: 100%;">
                © 2020 Copyright:
                <a class="text-body" href="{% url 'KnowIt:index' %}">KnowIt.com</a>
            </div>
        </div>

    </body>
</html>

cart/templates/cart/checkout.html
{% extends "BuyIt/layout.html" %}
{% load static %}

{%block body%}





{%endblock%}

members/templates/members/mugen.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>MUGAN</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    </head>
    <body style="background-image: url('{% static "KnowIt/bg_image_4.jpg" %}'); background-repeat: no-repeat; background-size: 1800px 900px;">
         {% if messages %}
            {% for message in messages %}
                <div class="alert alert-success" role="alert">
                  <strong>WELCOME! </strong> {{message}}
                </div>
            {% endfor %}
         {% endif %}
        <h1 style="color: white; margin-left: 3%; margin-top: 3%;"><svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-infinity" viewBox="0 0 16 16">
            <path d="M5.68 5.792 7.345 7.75 5.681 9.708a2.75 2.75 0 1 1 0-3.916ZM8 6.978 6.416 5.113l-.014-.015a3.75 3.75 0 1 0 0 5.304l.014-.015L8 8.522l1.584 1.865.014.015a3.75 3.75 0 1 0 0-5.304l-.014.015zm.656.772 1.663-1.958a2.75 2.75 0 1 1 0 3.916z"/>
        </svg>  MUGEN</h1>
        <div class="container" style="color: rgb(184, 180, 180); margin-top:10%;">
            <h3 style=" text-align:center; font-family: 'Fantacy', Copperplate;">Choose one</h5>
            <div class="spinner-grow" role="status" style="margin-top: 5%; margin-left: 30%">
                <span class="visually-hidden"></span>
            </div>
            <div style="display: inline; margin-left:4%">
                <a href="{% url 'KnowIt:index' %}" class="btn btn-outline-light btn-lg" style="height: 60px; width: 150px">Know <span style="color: aqua;">It</span></a>
                <a href="{% url 'BuyIt:index' %}" class="btn btn-outline-light btn-lg" style="margin-left: 3%;height: 60px; width: 150px">Buy <span style="color: aqua;">It</span></a>
            </div>
            <div class="spinner-grow" role="status" style="margin-left: 5%;">
                <span class="visually-hidden"></span>
            </div>
         </div>

    </body>
</html>